inventory_project/inventory_app/urls.py
from django.urls import path

from .views import detail, catalog, create, new_shipment, shipment_detail, shipments

app_name = 'inventory'

urlpatterns = [
    path('', catalog, name='catalog'),
    path('products/<int:item_id>/', detail, name='detail'),
    path('products/new/', create, name='add'),
    path('shipments/<int:shipment_id>/', shipment_detail, name='shipments'),
    path('shipments/', shipments, name='all_shipments'),
    path('shipments/new/', new_shipment, name='new_shipment'),
]

inventory_project/inventory_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('inventory_app.urls')),
    path('admin/', admin.site.urls),
]

inventory_project/inventory_app/models.py
from pyexpat import model
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.


class Location(models.Model):
    city = models.CharField(max_length=64)
    province = models.CharField(max_length=64)
    country = models.CharField(max_length=64)

    def __str__(self):
        return "{}, {}, {}".format(self.city, self.province, self.country)


class Weather(models.Model):
    location = models.OneToOneField(
        Location, on_delete=models.CASCADE, primary_key=True)
    temperature = models.FloatField(validators=[MinValueValidator(0.0)])
    pressure = models.IntegerField(validators=[MinValueValidator(0)])
    humidity = models.IntegerField(validators=[MinValueValidator(0)])

    def __str__(self):
        return "{} | {} | Temp: {}, Pressure: {}, Humidity: {}".format(self.location.id, self.location, self.temperature, self.pressure, self.humidity)


class Shipment(models.Model):
    first_name = models.CharField(max_length=32)

    last_name = models.CharField(max_length=32)

    company = models.CharField(max_length=32)

    street_address = models.CharField(max_length=64)

    city = models.CharField(max_length=32)

    state_province_region = models.CharField(max_length=32)

    postal_code = models.CharField(max_length=32)

    country = models.CharField(max_length=32)

    ship_code = models.CharField(max_length=20)

    tracking_number = models.CharField(max_length=20)

    def __str__(self):
        return "{} | {}".format(self.id, self.ship_code)


class Item(models.Model):
    name = models.CharField(max_length=255)

    price = models.FloatField(validators=[MinValueValidator(0.0)])

    quantity = models.IntegerField(validators=[MinValueValidator(0)])

    # Price x Quantity
    total = models.FloatField(validators=[MinValueValidator(0.0)])

    # 13 for International Article Number (European Article Number or EAN)
    upc = models.CharField(max_length=13)

    # City + Weather
    weather = models.ForeignKey(
        Weather, default=1, on_delete=models.DO_NOTHING)

    def __str__(self):
        return "{} | {}".format(self.id, self.name)


class ItemForShipment(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    shipment = models.ForeignKey(Shipment, on_delete=models.CASCADE)
    quantity = models.IntegerField(validators=[MinValueValidator(0)])

    def __str__(self):
        return "{} | {}".format(self.item.name, self.shipment.ship_code)

inventory_project/inventory_app/views.py
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.http import HttpResponseRedirect
from .models import Item, Shipment, ItemForShipment, Location, Weather
from .utils import generate_ship_code, generate_tracking_number
from .weather import get_city_weather
import threading


def detail(request, item_id):
    '''
    View for a specific inventory item

            Parameters:
                    request (HttpRequest): HttpRequest object that contains metadata about the request
                    item_id (int): ID of the inventory item

            Returns:
                    HttpResponseRedirect: Redirect the response
    '''

    if request.method == 'GET':
        item = get_object_or_404(Item, pk=item_id)
        locations = Weather.objects.all()
        return render(request, 'inventory_app/detail.html', {'item': item, 'locations': locations})

    elif request.method == 'POST':

        if request.POST.get("action") == "delete":
            item = Item.objects.get(pk=item_id)
            item.delete()

        else:
            name = request.POST.get("name")
            price = float(request.POST.get("price"))
            quantity = int(request.POST.get("quantity"))
            total = price * quantity
            upc = request.POST.get("upc")

            location_id = request.POST.get("dropdown")

            location = Location.objects.get(pk=location_id)
            weather = Weather.objects.get(location=location)

            obj, created = Item.objects.update_or_create(pk=item_id, defaults={
                'name': name,
                'price': price,
                'quantity': quantity,
                'total': total,
                'upc': upc,
                'weather': weather,
            })

        return HttpResponseRedirect(reverse('inventory:catalog'))


def create(request):
    '''
    View for adding an inventory item

            Parameters:
                    request (HttpRequest): HttpRequest object that contains metadata about the request

            Returns:
                    HttpResponseRedirect: Redirect the response
    '''

    if request.method == 'GET':
        locations = Weather.objects.all()
        return render(request, 'inventory_app/add.html', {'locations': locations})

    elif request.method == 'POST':

        name = request.POST.get("name")
        price = float(request.POST.get("price"))
        quantity = int(request.POST.get("quantity"))
        total = price * quantity
        upc = request.POST.get("upc")
        location_id = request.POST.get("dropdown")

        location = Location.objects.get(pk=location_id)
        weather = Weather.objects.get(location=location)

        item = Item(name=name, price=price,
                    quantity=quantity, total=total, upc=upc, weather=weather)
        item.save()

        return HttpResponseRedirect(reverse('inventory:catalog'))


def fetch_weather():
    '''
    View for fetching and updating the weather for 5 cities

            Parameters:
                    None

            Returns:
                    None
    '''

    locations = Location.objects.all()

    for location in locations:
        _, temperature, pressure, humidity = get_city_weather(location.city)

        obj, created = Weather.objects.update_or_create(
            location=location,
            defaults={'temperature': temperature,
                      'pressure': pressure, 'humidity': humidity}
        )

    return None


def catalog(request):
    '''
    View for inventory items

            Parameters:
                    request (HttpRequest): HttpRequest object that contains metadata about the request

            Returns:
                    render (HttpResponse): Returns an HttpResponse object of the given template rendered with the given context.
    '''

    thread = threading.Thread(target=fetch_weather)
    thread.start()
    all_items = Item.objects.filter(quantity__gt=0)
    context = {'all_items': all_items}
    return render(request, 'inventory_app/index.html', context)


def new_shipment(request):
    '''
    View for creating a new shipment

            Parameters:
                    request (HttpRequest): HttpRequest object that contains metadata about the request

            Returns:
                    HttpResponseRedirect: Redirect the response
    '''

    if request.method == 'GET':
        return render(request, 'inventory_app/add_shipment.html')

    elif request.method == 'POST':
        fname = request.POST.get("fname")
        lname = request.POST.get("lname")
        company = request.POST.get("company")
        street = request.POST.get("street")
        city = request.POST.get("city")
        province = request.POST.get("province")
        postal = request.POST.get("postal")
        country = request.POST.get("country")
        ship_code = generate_ship_code()
        tracking_number = generate_tracking_number()

        Shipment.objects.create(first_name=fname, last_name=lname, company=company, street_address=street, city=city,
                                state_province_region=province, postal_code=postal, country=country, ship_code=ship_code, tracking_number=tracking_number)

        return HttpResponseRedirect(reverse('inventory:all_shipments'))


def shipments(request):
    '''
    View for all shipments

            Parameters:
                    request (HttpRequest): HttpRequest object that contains metadata about the request

            Returns:
                    render (HttpResponse): Returns an HttpResponse object of the given template rendered with the given context.
    '''
    shipments = Shipment.objects.all()
    return render(request, 'inventory_app/shipments.html', {'shipments': shipments})


def shipment_detail(request, shipment_id):
    '''
    View for a specific shipment

            Parameters:
                    request (HttpRequest): HttpRequest object that contains metadata about the request
                    shipment_id: ID for a specific shipment
            Returns:
                    render (HttpResponse): Returns an HttpResponse object of the given template rendered with the given context.
    '''
    if request.method == 'GET':

        shipment = get_object_or_404(Shipment, pk=shipment_id)

        items = ItemForShipment.objects.filter(shipment__pk=shipment_id)

        item_ids = [item.item.id for item in items]

        catalog = Item.objects.exclude(
            id__in=item_ids).exclude(quantity__lte=0)

        return render(request, 'inventory_app/shipment.html', {'items': items, 'shipment': shipment, 'catalog': catalog})

    elif request.method == 'POST' and request.POST.get("delete"):

        id = request.POST.get("delete")
        item = Item.objects.get(pk=id)
        shipment = Shipment.objects.get(pk=shipment_id)
        itemForShipment = ItemForShipment.objects.get(
            item=item, shipment=shipment)

        item.quantity = item.quantity + itemForShipment.quantity
        item.total = item.price * item.quantity

        item.save()

        itemForShipment.delete()

        return HttpResponseRedirect(reverse('inventory:shipments', kwargs={'shipment_id': shipment_id}))

    elif request.method == 'POST' and request.POST.get("delete_shipment"):

        shipment_id = request.POST.get("delete_shipment")

        shipment = Shipment.objects.get(id=shipment_id)

        shipment.delete()

        return HttpResponseRedirect(reverse('inventory:all_shipments'))

    else:
        item_id = request.POST.get("dropdown")
        quantity = int(request.POST.get("quantity"))

        item = Item.objects.get(pk=item_id)
        shipment = Shipment.objects.get(pk=shipment_id)

        item.quantity = item.quantity - quantity
        item.total = item.price * item.quantity

        item.save()

        obj, created = ItemForShipment.objects.update_or_create(
            item=item, shipment=shipment, defaults={
                'quantity': quantity
            }
        )

        return HttpResponseRedirect(reverse('inventory:shipments', kwargs={'shipment_id': shipment_id}))

inventory_project/inventory_app/templates/inventory_app/add.html
{% extends "inventory_app/base.html" %}
{% block title %} Add Item {% endblock %}
{% block content %}
<div class="row">
    <div class="card-panel">
        <h1 class="indigo-text darken-4 center-align">Add Item</h1>
        <form action="{% url 'inventory:add' %}" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="input-field col s12">
                    <input placeholder="Coca-Cola 2L" name="name" id="name" type="text" required>
                    <label for="name">Item</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <input placeholder="$1.99" name="price" id="price" type="number" step="0.01" min="0.00" data-error="2 decimal places" required>
                    <label for="price">Price</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <input placeholder="100" name="quantity" id="quantity" type="number" required>
                    <label for="quantity">Quantity</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <input placeholder="036000291452" name="upc" id="upc" type="text" data-length="12" maxlength="12" required>
                    <label for="upc">UPC (Barcode)</label>
                </div>
            </div>
            <select name="dropdown" class="browser-default" required>
                <option value="" disabled selected>Choose city</option>
                {% if locations %}
                {% for location in locations %}
                <option value="{{location.location.id}}">{{location.location.city}}</option>
                {% endfor %}
                {% endif %}
            </select>
            <hr>
            <h1></h1>
            <button class="btn waves-effect waves-light indigo darken-4" type="submit" name="action">Submit
            <i class="material-icons right">send</i>
            </button>
        </form>
    </div>
</div>
{% endblock %}

inventory_project/inventory_app/templates/inventory_app/add_shipment.html
{% extends "inventory_app/base.html" %}
{% block title %} Create Shipment {% endblock %}
{% block content %}
<div class="row">
    <div class="card-panel">
        <h1 class="indigo-text darken-4 center-align">Create Shipment</h1>
        <form action="{% url 'inventory:new_shipment' %}" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="input-field col s6">
                    <input placeholder="John" name="fname" id="fname" type="text" required>
                    <label for="fname">First Name</label>
                </div>
                <div class="input-field col s6">
                    <input placeholder="Doe" name="lname" id="lname" type="text" required>
                    <label for="lname">Last Name</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <input placeholder="Acme Corporation" name="company" id="company" type="text" required>
                    <label for="company">Company</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <input placeholder="11022 Jasper Ave" name="street" id="street" type="text" required>
                    <label for="name">Street Address</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s6">
                    <input placeholder="Edmonton" name="city" id="city" type="text" required>
                    <label for="name">City</label>
                </div>
                <div class="input-field col s6">
                    <input placeholder="Alberta" name="province" id="province" type="text" required>
                    <label for="name">Province</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s6">
                    <input placeholder="T5K 2N8" name="postal" id="postal" type="text" required>
                    <label for="name">Postal Code</label>
                </div>
                <div class="input-field col s6">
                    <input placeholder="Canada" name="country" id="country" type="text" required>
                    <label for="name">Country</label>
                </div>
            </div>
            <button class="btn waves-effect waves-light indigo darken-4" type="submit" name="action">Submit
            <i class="material-icons right">send</i>
            </button>
        </form>
    </div>
</div>
{% endblock %}

inventory_project/inventory_app/templates/inventory_app/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %} Inventory System {% endblock %}</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    </head>
    <body>
        <nav>
            <div class="indigo darken-4 nav-wrapper">
                <a href="{% url 'inventory:catalog' %}" class="brand-logo center">Inventory System</a>
                <ul id="nav-mobile" class="right hide-on-med-and-down">
                    <li><a href="{% url 'inventory:catalog' %}">Catalog</a></li>
                    <li><a href="{% url 'inventory:add' %}">Add Item</a></li>
                    <li><a href="{% url 'inventory:all_shipments' %}">Shipments</a></li>
                    <li><a href="{% url 'inventory:new_shipment' %}">Create Shipment</a></li>
                </ul>
            </div>
        </nav>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    </body>
</html>

inventory_project/inventory_app/templates/inventory_app/detail.html
{% extends "inventory_app/base.html" %}
{% block title %} {{item.name}} {% endblock %}
{% block content %}
<div class="row">
    <form action="{% url 'inventory:detail' item.id %}" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="input-field col s12">
                <input placeholder="Coca-Cola 2L" name="name" id="name" type="text" value="{{ item.name }}" required>
                <label for="name">Item</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s12">
                <input placeholder="$1.99" name="price" id="price" type="number" step="0.01" min="0.00" data-error="2 decimal places" value="{{ item.price }}" required>
                <label for="price">Price</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s12">
                <input placeholder="100" name="quantity" id="quantity" type="number" value="{{ item.quantity }}" required>
                <label for="quantity">Quantity</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s12">
                <input placeholder="036000291452" name="upc" id="upc" type="text" data-length="12" maxlength="12" value="{{ item.upc }}" required>
                <label for="upc">UPC (Barcode)</label>
            </div>
        </div>
        <select name="dropdown" class="browser-default" required>
            <option value="" disabled selected>Choose city</option>
            {% if locations %}
            {% for location in locations %}
            {% if location.location.city == item.weather.location.city %}
            <option value="{{location.location.id}}" selected>{{location.location.city}}</option>
            {% else %}
            <option value="{{location.location.id}}">{{location.location.city}}</option>
            {% endif %}
            {% endfor %}
            {% endif %}
        </select>
        <h1></h1>
        <button class="btn waves-effect waves-light indigo darken-4" type="submit" name="action" value="save">Save
        <i class="material-icons right">save</i>
        </button>
        <button class="btn waves-effect waves-light red darken-4" type="submit" name="action" value="delete">Delete
        <i class="material-icons right">delete</i>
        </button>
    </form>
</div>
{% endblock %}

inventory_project/inventory_app/templates/inventory_app/index.html
{% extends "inventory_app/base.html" %}
{% block content %}
{% if all_items %}
<div class="row">
    {% for item in all_items %}
    <div class="col s12 m12 l4">
        <div class="card">
            <div class="card-image">
                <img src="https://storage.googleapis.com/justinmonteza/Inventory/Inventory.jpg">
                <span class="card-title"><b>{{item.name}}</b></span>
            </div>
            <div class="card-content">
                <h6><b>Price:</b> ${{item.price}}</h6>
                <h6><b>Quantity:</b> {{item.quantity}}</h6>
                <h6><b>Total Value:</b> ${{item.total|floatformat:2}}</h6>
                <h6><b>UPC:</b> {{item.upc}}</h6>
                &nbsp;
                <h6><b>City: </b>{{item.weather.location.city}} </h6>
                <h6><b>Temperature: </b> {{item.weather.temperature}} &#8451;</h6>
                <h6><b>Pressure: </b> {{item.weather.pressure}} hPa</h6>
                <h6><b>Humidity: </b> {{item.weather.humidity}}%</h6>
            </div>
            <div class="card-action">
                <a class="indigo-text indigo-darken-4" href="{% url 'inventory:detail' item.id %}">Details</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
<h1 class="center-align"> Inventory is empty </h1>
{% endif %}
{% endblock %}

inventory_project/inventory_app/templates/inventory_app/shipment.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Shipment #{{shipment.id}}</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    </head>
    <body>
        <nav>
            <div class="indigo darken-4 nav-wrapper">
                <a href="{% url 'inventory:catalog' %}" class="brand-logo center">Inventory System</a>
                <ul id="nav-mobile" class="right hide-on-med-and-down">
                    <li><a href="{% url 'inventory:catalog' %}">Catalog</a></li>
                    <li><a href="{% url 'inventory:add' %}">Add Item</a></li>
                    <li><a href="{% url 'inventory:all_shipments' %}">Shipments</a></li>
                    <li><a href="{% url 'inventory:new_shipment' %}">Create Shipment</a></li>
                </ul>
            </div>
        </nav>
        <div class="row">
            <div class="col l8">
                <div class="card-panel large indigo darken-4 white-text">
                    <h1 class="center-align">Add Item to Shipment #{{shipment.id}}</h1>
                    {% if catalog %}
                    <form action="{% url 'inventory:shipments' shipment.id %}" method="post">
                        {% csrf_token %}
                        <select name="dropdown" class="browser-default" required>
                            <option value="" disabled selected>Choose item</option>
                            {% if catalog %}
                            {% for item in catalog %}
                            <option value="{{item.id}}">{{item.name}} (Available: {{item.quantity}})</option>
                            {% endfor %}
                            {% endif %}
                        </select>
                        &nbsp;
                        <div class="row">
                            <div class="input-field col s12">
                                <input class="white-text" placeholder="100" name="quantity" id="quantity" type="number" required>
                                <label class="white-text" for="quantity">Quantity</label>
                            </div>
                        </div>
                        <button class="btn waves-effect waves-light white indigo-text indigo-darken-4" type="submit" name="action">Add
                        <i class="material-icons right">add</i>
                        </button>
                    </form>
                    {% else %}
                    <h6 class="center-align">No inventory items to add</h6>
                    {% endif %}
                </div>
            </div>
            <div class="col l4">
                <div class="card-panel indigo darken-4 white-text large">
                    <h1 class="center-align">Shipment #{{shipment.id}}</h1>
                    <form action="{% url 'inventory:shipments' shipment.id %}" method="post">
                        {% csrf_token %}
                        <div class="center-align">
                            <button class="btn waves-effect waves-light red darken-4" type="submit" name="delete_shipment" value="{{shipment.id}}">Delete
                            <i class="material-icons right">delete</i>
                            </button>
                        </div>
                    </form>
                    <h5> Receiver <br> {{shipment.first_name}} {{shipment.last_name}} </h5>
                    <h5> Company <br> {{shipment.company}} </h5>
                    <h5> Address <br> {{shipment.street_address}} {{shipment.city}} <br> {{shipment.state_province_region}} {{shipment.postal_code}} <br> {{shipment.country}} </h5>
                    <hr>
                    <h5> Ship Code <br> {{shipment.ship_code}} </h5>
                    <h5> Tracking Number <br> {{shipment.tracking_number}} </h5>
                    <hr>
                    <!-- <ul> -->
                    <form action="{% url 'inventory:shipments' shipment.id %}" method="post">
                        {% csrf_token %}
                        {% for item in items %}
                        <h5>         <button class="btn waves-effect waves-light red darken-4" type="submit" name="delete" value="{{item.item.id}}">Delete
                            <i class="material-icons right">delete</i>
                            </button>
                            &nbsp; {{item.item.name}} ({{item.quantity}})
                        </h5>
                        {% endfor %}
                    </form>
                    <!-- </ul> -->
                </div>
            </div>
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <script type="text/javascript">
            document.addEventListener('DOMContentLoaded', function() {
            var elems = document.querySelectorAll('select');
            var instances = M.FormSelect.init(elems, options);
            });
        </script>
    </body>
</html>

inventory_project/inventory_app/templates/inventory_app/shipments.html
{% extends "inventory_app/base.html" %}
{% block title %} Shipments {% endblock %}
{% block content %}
{% if shipments %}
<div class="row">
    {% for shipment in shipments %}
    <div class="col s12 m12 l4">
        <div class="card">
            <div class="card-image">
                <img src="https://storage.googleapis.com/justinmonteza/Inventory/Shipment.jpg">
                <span class="card-title"><b>Shipment #{{shipment.id}}</b></span>
            </div>
            <div class="card-content">
                <h6><b>Receiver</b> <br>{{shipment.first_name}} {{shipment.last_name}}</h6>
                <h6><b>Shipping Code</b> <br> {{shipment.ship_code}}</h6>
                <h6><b>Tracking Number</b> <br> {{shipment.tracking_number}}</h6>
                <h6><b>Address</b> <br> {{shipment.street_address}} <br> {{shipment.city}} {{shipment.state_province_region}} <br> {{shipment.country}} {{shipment.postal_code}} </h6>
            </div>
            <div class="card-action">
                <a class="indigo-text indigo-darken-4" href="{% url 'inventory:shipments' shipment.id %}">Details</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
<h1 class="center-align"> No shipments are available </h1>
{% endif %}
{% endblock %}